### ISSUE TITLE
[Bug]: 見出しのスタイル適用範囲が広すぎる

### ISSUE THREAD

**Issue by tsuna-can-se** [tsuna-can-se/md2pdf-doc-template#68]
### 期待する動作

markdown-body クラスの中にある見出しに対してのみ、スタイルを適用してほしい。

### 現在の動作

以下のようになっており、見出しのスタイル適用範囲が広すぎる。

```css
.markdown-body h2,
h3,
h4,
h5,
h6 {
    page-break-after: avoid;
}
```

### 考えられる解決策

`h3` ～ `h6` にも `.markdown-body` の限定をするべき。

### 再現手順

なし

### 環境

環境不問

### 確認

- [x] 報告しようとしているバグがセキュリティ関連の問題、脆弱性に関するものではないことを確認しました。セキュリティ関連の問題、脆弱性の場合は [Open a draft security advisory](../security/advisories/new) から報告してください。
- [x] 報告しようとしているバグが [Issues](../issues) および [Discussions](../discussions) に登録されていないことを確認しました。
- [x] 私たちの [行動規範](../?tab=coc-ov-file) に従うことを同意します。
